### PR TITLE
fix(core): Fixes getEditUrl to build URLs w/URL vs just path.join

### LINKED ISSUE #253: Edit links are broken
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Edit links on various pages are broken because they are built using `path.join` which does not work properly for URLs.

### Steps to reproduce

1. Put an `editUrl` into config like `https://github.com/drub0y/myEventCatalog/edit/master`
2. Publish your site anywhere (including localhost)
3. Click an edit button
4. Observe that an incorrect URL is built like: `http://localhost:3000/github.com/drub0y/myEventCatalog/services/MyService/index.md`

### Expected behavior

I expect the edit URL to be built correctly as: `https://github.com/drub0y/myEventCatalog/edit/master/services/MyService/index.md`.

### Actual behavior

Builds wrong URL that ends up going to a 404.

### Your environment

- EventCatalog version used: 0.2.14
- Environment name and version: node v16.14.0, any browser
- Operating system and version: OSX 12.3.1

### PR DESCRIPTION
**Pull request by drub0y**
Fixes #253

## Motivation

Want edit links to work for everyone. 😁

### Have you read the [Contributing Guidelines on pull requests](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, all good. 👍

### CODE REVIEW

File: packages/eventcatalog/hooks/EventCatalog.tsx [hunk 1]
```diff
@@ -26,7 +26,13 @@ export const useUser = () => {
 
 export const useUrl = () => {
   const config = useConfig();
-  const getEditUrl = (url: string) => path.join(config.editUrl, url);
+  const getEditUrl = (url: string) => {
+    const editBaseUrl = new URL(config.editUrl);
+
+    editBaseUrl.pathname = path.join(editBaseUrl.pathname, url);
```
Comment (drub0y) [inline packages/eventcatalog/hooks/EventCatalog.tsx:32]: Ok to use `path.join` just on the pathname portion, but we need to isolate that by using the `URL` class first so it doesn't clobber anything else about the base URL.

**Comment by boyney123** [comment]
Thanks again @drub0y , I tested it out seems good to me! Although I couldnt replicate the bug... not sure why, but this solution works too and if it solves your issue I'm happy to merge :)

**Comment by boyney123** [comment]
@allcontributors add @drub0y for code
